CB-11 created footer and contact page
CRANKBIT/CrankBit-FrontEnd pull request #31
Opened 2023-06-12 04:17 UTC by SteveGuoh

Initial code Version of footer and Contact page

2023-06-12 22:31 UTC, LH-Song requested changes
很多inline style css 混用统一改为tailwind

2023-06-12 22:31 UTC, LH-Song commented on src/layouts/Footer/components/Footer-Container/FooterContainer.tsx
> +import NavLink from './components/NavLink/NavLink';
```suggestion
import NavLink from '@/components/NavLink';
```
加上index 索引文件 就可以不用路径里面写两遍

2023-06-12 22:31 UTC, LH-Song commented on src/layouts/Footer/components/Footer-Container/FooterContainer.tsx
> +        <div className='bg-[#03111B] text-white h-96 mx-auto flex flex-col justify-center max-w-7xl'>
```suggestion
        <div className='bg-[#03111B] text-white h-[96px] mx-auto flex justify-center max-w-7xl'>
```
Tailwind 默认height里面应该没有96这么大的，默认格式-x相当于 4X px，没有默认配置的可以用[]设置。需要用到flex col 才能实现吗？除非希望渲染方式是一列一列的情况，一般我们不需要使用 flex-col ，flex 默认排序方式就可以满足

2023-06-12 22:31 UTC, LH-Song commented on src/layouts/Footer/components/Footer-Container/FooterContainer.tsx
> +        <div className='justify-center items-center z-10 pt-14 mx-auto'>
```suggestion
        <div className='z-10 pt-14 mx-auto'>
```

justify-center items-center 只有在 flex的情况下才会起作用

2023-06-12 22:31 UTC, LH-Song commented on src/pages/Contact/components/Upperbox/components/MessageBox/Messagebox.tsx
> +          }}
use tailwind instead

2023-06-13 01:35 UTC, LH-Song requested changes

2023-06-13 01:35 UTC, LH-Song commented on src/layouts/Footer/components/Footer-Container/components/ScrollUpButton/ScrollUpButton.tsx
> +    <div className='flex justify-center items-center h-10 w-10 bg-[#007ad333] rounded-full text-[#007AD3]'>
bg颜色 tailwind config 文件有设置好的

2023-06-15 10:42 UTC, SteveGuoh commented on src/layouts/Footer/components/Footer-Container/FooterContainer.tsx
> +import NavLink from './components/NavLink/NavLink';
Resolved

2023-06-15 10:42 UTC, SteveGuoh commented on src/layouts/Footer/components/Footer-Container/FooterContainer.tsx
> +const FooterContainer: FC = () => {
Resolved

2023-06-15 10:43 UTC, SteveGuoh commented on src/layouts/Footer/components/Footer-Container/FooterContainer.tsx
> +        <div className='bg-[#03111B] text-white h-96 mx-auto flex flex-col justify-center max-w-7xl'>
除了 flex-col 都resolved, flex col负责三排组件的居中

2023-06-15 10:43 UTC, SteveGuoh commented on src/layouts/Footer/components/Footer-Container/FooterContainer.tsx
> +        <div className='text-base space-x-9 pt-28 mx-auto'>
Resolved

2023-06-15 10:43 UTC, SteveGuoh commented on src/layouts/Footer/components/Footer-Container/FooterContainer.tsx
> +        <div className='justify-center items-center z-10 pt-14 mx-auto'>
Resolved

2023-06-15 10:44 UTC, SteveGuoh commented on src/layouts/Footer/components/Footer-Container/components/NavLink/NavLink.tsx
> +import handleScrollToTop from '../HandleScrollToTop/HandleScrollToTop';
Resolved

2023-06-15 10:44 UTC, SteveGuoh commented on src/pages/Contact/Contact.tsx
> +        </>
Resolved

2023-06-15 10:44 UTC, SteveGuoh commented on src/pages/Contact/components/Lowerbox/Lowerbox.tsx
> +        backgroundColor: '#0A2030',
Resolved

2023-06-15 10:44 UTC, SteveGuoh commented on src/pages/Contact/components/Upperbox/Upperbox.tsx
> +          <TextInput width={250} labelName="Name" />
Resolved

2023-06-15 10:44 UTC, SteveGuoh commented on src/pages/Contact/components/Upperbox/components/MessageBox/Messagebox.tsx
> +          }}
Resolved

2023-06-16 05:01 UTC, Qiming-Liu commented on .DS_Store
Please remove these files

2023-06-16 05:24 UTC, SteveGuoh commented on src/layouts/Footer/components/Footer-Container/components/NavLink/NavLink.tsx
> +import handleScrollToTop from '../HandleScrollToTop/HandleScrollToTop';
resolved, thanks

2023-06-17 15:28 UTC, Qiming-Liu approved these changes

2023-06-17 15:28 UTC, merged