Cb 3 landing page hero features pricing UI
CRANKBIT/CrankBit-FrontEnd pull request #44
Opened 2023-06-14 13:39 UTC by TaoGit2023

update CB3

2023-06-14 13:58 UTC, smarthulala requested changes

2023-06-15 02:48 UTC, TaoGit2023 commented on src/pages/Home/components/Features/components/DisplayCards/components/FeatureCard/FeatureCard.tsx
> +  <div className="w-60 h-40 shadow-2xl m-5 rounded-lg p-10">
margin 是为了每个卡之间有距离，padding 是为了使内容离边远一点

2023-06-15 02:52 UTC, TaoGit2023 commented on src/pages/Home/components/Pricing/components/DisplayPlans/DisplayPlans.tsx
> +        <button type="button" className="text-center text-base text-[#007AD3] w-60 border py-2.5 rounded-md border-[#007AD3] bg-white">Choose Plan</button>
这个我还不会用，等开会的时候请教一下。

2023-06-16 04:38 UTC, Qiming-Liu approved these changes

2023-06-16 04:41 UTC, merged