CB-5 Login for company
CRANKBIT/CrankBit-FrontEnd pull request #47
Opened 2023-06-15 07:10 UTC by Ry4n6137

2023-06-15 12:33 UTC, Qiming-Liu commented
What's the router url for this page?

2023-06-15 14:29 UTC, smarthulala requested changes

2023-06-15 14:29 UTC, smarthulala commented on src/pages/Login/components/LoginForCompany/FormBuilder/FormBuilder.tsx
> +      <div className="text-[#FFFFFF] w-[131px] h-[27px] text-[22px] font-medium leading-[22.63px]">
#FFFFFF equals white
leading-[22.63px] is this necessary? use 22px or w-6

2023-06-15 14:29 UTC, smarthulala commented on src/pages/Login/components/LoginForCompany/LoginPage/LoginPage.tsx
> +          <p className="text-[16px] leading-[19px] font-medium not-italic">Work email</p>
```suggestion
          <p className="text-4 leading-5 font-medium not-italic">Work email</p>
```

2023-06-15 14:29 UTC, smarthulala commented on src/pages/Login/components/LoginForCompany/LoginPage/LoginPage.tsx
> +            className="box-border pl-[3px] w-[280px] h-[44px] mb-[24px] border-solid border-[1px] border-[#03111B] rounded-[5px]
```suggestion
            className="box-border pl-[3px] w-[280px] h-11 mb-6 border border-[#03111B] rounded-[5px]
```

2023-06-15 14:29 UTC, smarthulala commented on src/pages/Login/components/LoginForCompany/LoginPage/LoginPage.tsx
> +          <p className="text-[16px] leading-[19px] font-medium not-italic">Your site</p>
```suggestion
          <p className="text-4 leading-[19px] font-medium not-italic">Your site</p>
```

2023-06-15 14:29 UTC, smarthulala commented on src/pages/Login/components/LoginForCompany/LoginPage/LoginPage.tsx
> +            className="box-border pl-[3px] w-[280px] h-[44px] mb-[24px] border-solid border-[1px] border-[#03111B] rounded-[5px]
border-solid border-[1px] === border

2023-06-15 14:29 UTC, smarthulala commented on src/pages/Login/components/LoginForCompany/LoginPage/LoginPage.tsx
> +        className="w-[280px] h-[50px] text-[#FFFFFF] bg-[#007AD3] text-[18px] leading-[22px] font-bold rounded-[5px] mt-5"
customised tailwind pixels that is a multiple of 4, there is a default tailwind value
for example: 20px === 5, 16px === 4

2023-06-16 04:10 UTC, Ry4n6137 commented
> What's the router url for this page?

I've added it

2023-06-16 04:12 UTC, Ry4n6137 commented
I‘m waiting for rereview

2023-06-16 04:50 UTC, Qiming-Liu requested changes

2023-06-16 04:50 UTC, Qiming-Liu commented on src/pages/Login/components/LoginForCompany/LoginPage/LoginPage.tsx
> +            placeholder="  Alonso@mail.com"
Should we remove this space?

2023-06-16 04:51 UTC, merged