CB-6
CRANKBIT/CrankBit-FrontEnd pull request #70
Opened 2023-07-02 07:43 UTC by cansibi

2023-07-02 07:45 UTC, cansibi commented
ready to review

2023-07-02 07:46 UTC, cansibi commented
cb-56 included

2023-07-05 09:03 UTC, cansibi commented
ready to review

2023-07-06 06:39 UTC, LH-Song commented on src/pages/CreateAccount/CreateAccount.tsx
> +import React, { ChangeEvent, FC, FormEvent, useState } from 'react'
```suggestion
import React, { FC, FormEvent, useState } from 'react'
```

2023-07-06 06:40 UTC, LH-Song commented on src/pages/CreateAccount/CreateAccount.tsx
> +  const handleInputChange =
```suggestion
const inputClassName =
    'w-full border border-gray-300 rounded-md px-3 py-2 mt-1 focus:outline-none focus:ring-1 focus:ring-gray-400'
    
  const handleInputChange =
```

2023-07-06 06:41 UTC, LH-Song commented on src/pages/CreateAccount/CreateAccount.tsx
> +    (setValue: React.Dispatch<React.SetStateAction<string>>, validatePassword = false) =>
```suggestion
    (setValue: React.Dispatch<React.SetStateAction<string>>,) =>
```

2023-07-06 06:42 UTC, LH-Song commented on src/pages/CreateAccount/CreateAccount.tsx
> +    }
```suggestion
     let errorMessage = ''

      if (value.length < 6 || !/\d/.test(value) || !/[a-zA-Z]/.test(value)) {
        errorMessage = 'At least 6 characters with 1 letter'
      }

      setPasswordError(value !== '' ? errorMessage : '')
      
    }
```

2023-07-06 06:46 UTC, LH-Song commented on src/pages/CreateAccount/CreateAccount.tsx
> +            onChange={handleInputChange(setPassword, true)}
```suggestion
              onChange={handleInputChange(setPassword)}
```

2023-07-06 06:46 UTC, LH-Song commented on src/pages/CreateAccount/CreateAccount.tsx
> +          </div>
```suggestion
     {passwordError && (
              <Typography className="caption" color="error">
                {passwordError}
              </Typography>
            )}
```

2023-07-06 06:47 UTC, LH-Song requested changes
👖

2023-07-06 09:55 UTC, LH-Song approved these changes
LGTM🚀

2023-07-06 09:56 UTC, merged